"""Part 2: Weibull clutter amplitudes generated by inverse-CDF sampling.

For shape c_w and scale lambda_w, E[X^2] = lambda_w^2 * Gamma(1+2/c_w).
Choosing the scale from Pc preserves mean power when changing the shape.
c_w=2 is Rayleigh; smaller shapes have heavier tails than this baseline.
This model illustrates amplitude statistics, not specific terrain types.
"""

import numpy as np
from scipy.special import gammaln
from scipy.stats import weibull_min

from radar_utils import CNR_dB, Pc, c_w, parse_args, save_figure


def main(output_dir="figures", show=True):
    import matplotlib.pyplot as plt
    rng = np.random.default_rng(42)
    N_samples = 100_000
    gamma_val = np.exp(gammaln(1 + 2 / c_w))
    lambda_w = np.sqrt(Pc / gamma_val)

    # Inverse CDF: U ~ Uniform[0,1) -> X = lambda_w*(-log(1-U))**(1/c_w).
    U = rng.random(N_samples)
    clutter_amp = lambda_w * (-np.log1p(-U)) ** (1 / c_w)
    clutter_scipy = weibull_min.rvs(c=c_w, scale=lambda_w, size=N_samples, random_state=99)
    mean_sim = np.mean(clutter_amp)
    std_sim = np.std(clutter_amp)
    power_sim = np.mean(clutter_amp**2)
    mean_theory = lambda_w * np.exp(gammaln(1 + 1 / c_w))
    var_theory = Pc - mean_theory**2
    power_theory = Pc
    power_error_dB = 10 * np.log10(power_sim / power_theory)

    print("PART 2 - WEIBULL CLUTTER")
    print(f"Shape: {c_w} | Scale: {lambda_w:.4e} | Samples: {N_samples:,}")
    print(f"{'Statistic':<22} {'Simulation':>14} {'Theory':>14}")
    for label, sim, theory in [("Mean", mean_sim, mean_theory), ("Standard deviation", std_sim, np.sqrt(var_theory)), ("Mean power (W)", power_sim, power_theory)]:
        print(f"{label:<22} {sim:>14.5e} {theory:>14.5e}")
    print(f"Power error: {power_error_dB:+.3f} dB")
    print(f"Independent SciPy sample power error: {10*np.log10(np.mean(clutter_scipy**2)/Pc):+.3f} dB")

    x_max = lambda_w * 4.5
    x_pdf = np.linspace(0, x_max, 2000)
    pdf_theory = weibull_min.pdf(x_pdf, c=c_w, scale=lambda_w)
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    fig.suptitle(f"Weibull clutter | Shape {c_w:g} | CNR {CNR_dB:.0f} dB | {N_samples:,} samples", fontweight="bold")
    ax = axes[0]
    ax.hist(clutter_amp, bins=100, density=True, alpha=0.6, label="Inverse-CDF samples")
    ax.plot(x_pdf, pdf_theory, color="red", lw=2, label="Theoretical PDF")
    ax.axvline(mean_sim, color="orange", ls="--", label="Sample mean")
    ax.axvline(mean_theory, color="green", ls=":", label="Theoretical mean")
    ax.set_title("Amplitude histogram and theoretical density")
    c_values = [1.0, 1.5, 2.0, 3.0]
    labels_c = ["1.0 (exponential)", "1.5 (heavier tail)", "2.0 (Rayleigh)", "3.0 (lighter tail)"]
    for cv, lbl in zip(c_values, labels_c):
        lv = np.sqrt(Pc / np.exp(gammaln(1 + 2 / cv)))
        axes[1].plot(x_pdf, weibull_min.pdf(x_pdf, c=cv, scale=lv), lw=2, label=f"Shape {lbl}")
    axes[1].set_title("Shape comparison at equal mean power")
    for ax in axes:
        ax.set(xlabel="Power-normalized amplitude (sqrt(W))", ylabel="Probability density", xlim=(0, x_max))
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)
    save_figure(fig, "part2_clutter_generation.png", output_dir, show)
    return {"power_error_dB": power_error_dB}


if __name__ == "__main__":
    args = parse_args(__doc__)
    if args.no_show:
        import matplotlib
        matplotlib.use("Agg")
    main(args.output_dir, show=not args.no_show)
